### ISSUE TITLE
On MacOS, file choose does not go away, need to exit Julia first

### ISSUE THREAD

**Issue by fingolfin** [Suavesito-Olimpiada/NativeFileDialog.jl#1]
I dev'ed this package (at commit 5d1905b7fe2dfe8c1b3dcdd8359368a4ab823c00) plus `NativeFileDialog_jll v1.1.6+1`, in Julia 1.6.3 running on macOS 10.14.6.

Executing `NativeFileDialog.pick_file()` from the Julia REPL shows a file chooser dialog just fine, and I used it to select a file. After selecting the file, the correct path is returned. However, the chooser dialog never is removed; moving the mouse over it now turns the mouse into a beach ball (indicating the process owning the dialog does not process events). The only way to get rid of the dialog seems to be ending the owner process (i.e., julia).

**Comment by alecloudenback** [comment]
also works for me

**Comment by fingolfin** [comment]
Still doesn't work for me with version v1.1.6+2 of the JLL

@alecloudenback which macOS version, though?
