### ISSUE TITLE
Compatibility with FilePathsBase

### ISSUE THREAD

**Issue by alecloudenback** [Suavesito-Olimpiada/NativeFileDialog.jl#3]
I haven't done much heavy lifting with file paths yet, but if I did I understand having a typed file system would be beneficial for reducing errors and improving cross-system compatbility. I'm not sure exactly what it would look like, but compatibility with [FilePaths.jl](https://github.com/rofinn/FilePaths.jl) could be useful.

E.g. the following doesn't work:

```julia-repl
julia> using FilePathsBase, NativeFileDialog

julia> pick_file(;path=home(), filterlist="")
```

results in:

```julia-repl

julia> pick_file(;path=home(), filterlist="")
ERROR: MethodError: no method matching pointer(::PosixPath)
Closest candidates are:
  pointer(::SuiteSparse.CHOLMOD.Dense{Tv}) where Tv at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/SuiteSparse/src/cholmod.jl:358
  pointer(::Random.UnsafeView) at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/Random/src/RNGs.jl:501
  pointer(::PermutedDimsArray, ::Integer) at permuteddimsarray.jl:61
  ...
Stacktrace:
 [1] pick_file(; path::PosixPath, filterlist::String)
   @ NativeFileDialog ~/.julia/packages/NativeFileDialog/RzsbC/src/NativeFileDialog.jl:52
 [2] top-level scope
   @ REPL[15]:1
```

**Comment by Suavesito-Olimpiada** [comment]
This looks like a great idea. I'll be adding compatibility with FilePaths.jl (but if anyone beat me to it there will be no tears). ;)

**Comment by Suavesito-Olimpiada** [comment]
That sounds like a good idea. :)

**Comment by Suavesito-Olimpiada** [comment]
Done on [this](https://github.com/Suavesito-Olimpiada/NativeFileDialog.jl/commit/5e78e60b137527b3fa2da828ba8d441291cf3ee9) commit.
