### ISSUE TITLE
Unable to install in Debian.

### ISSUE THREAD

**Issue by VentGrey** [Suavesito-Olimpiada/NativeFileDialog.jl#7]
Pkg seems to be struggling with package versions resolving in Julia 1.5.3 (`Debian ⛬  julia/1.5.3+dfsg-3`). This version of julia is not downloaded from the official Julia page, it is the one packaged by Debian.

I don't know how much information I can provide on this issue except a few outputs that *may* be useful:

## Pkg output

```
(@v1.5) pkg> add NativeFileDialog
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package NativeFileDialog_jll [94d9ae2c]:
 NativeFileDialog_jll [94d9ae2c] log:
 ├─possible versions are: 1.1.6 or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with NativeFileDialog [e1fe445b] to versions: 1.1.6 — no versions left
   └─NativeFileDialog [e1fe445b] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
```

## Julia versioninfo

```
$ julia -e "using InteractiveUtils; versioninfo()" 
Julia Version 1.5.3
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
```

**Comment by Suavesito-Olimpiada** [comment]
Researching more about this I found that the `experimental` option used for platform selection on `build_tarballs.jl` for `NativeFileDialog_jll` is not available for Julia version `< v1.6`. This option is used when building for Mac users with ARM processors.

I think most people should use the latest version with official binaries. Given my opinion and that making this compatible with `<v1.5"` would mean dropping support for Mac users with new architecture I'll fall on changing the `compat` for this lib to just using Julia `>= v1.6`. And mark this as WONTFIX.

(Also `v1.0` was just marked as unmaintained and `v1.6` is new LTS, making older releases even less interesting to maintain.)
