### ISSUE TITLE
transfer to JuliaGraphics org?

### ISSUE THREAD

**Issue by stevengj** [Suavesito-Olimpiada/NativeFileDialog.jl#9]
Might be worth transferring to the https://github.com/JuliaGraphics org (where the other GUI packages seem to live) to allow additional maintainers?

cc @timholy

**Comment by Suavesito-Olimpiada** [comment]
Yeah, gladly to do this, just that I don't know how to transfer repositories. 😅

**Comment by stevengj** [comment]
Once someone in the JuliaGraphics organization gives you permission, it's a simple matter of clicking "Transfer" in the Settings: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization

**Comment by Suavesito-Olimpiada** [comment]
Perfect, then I'll wait for the invitation to JuliaGraphics.

**Comment by timholy** [comment]
Invite sent. I'm not entirely sure the permissions are set properly, so if you have any difficulty in doing the transfer, please let us know.

**Comment by Suavesito-Olimpiada** [comment]
Effectively, I cannot transfer the repository as it says insufficient permissions. 😅

**Comment by timholy** [comment]
Rats. OK, I changed your permissions. Can you try again?

**Comment by Suavesito-Olimpiada** [comment]
I think we can call this successful.
